### ISSUE TITLE
"LibNetworkStack Read Error"

### ISSUE THREAD

**Issue by AngelTechnic** [AlexIIL/LibNetworkStack#16]
[latest.log](https://github.com/AlexIIL/LibNetworkStack/files/15211326/latest.log)

This happens whenever I attempt to join a server, and also is apparently what disconnected me from the server while I was playing it earlier. I was told to report it to you.

**Comment by Kneelawk** [comment]
This looks like a WiredRedstone bug. I'll see if I can get a fix out.

**Comment by Kneelawk** [comment]
Ok, try updating Wired Redstone to `0.7.8`. Hopefully that should fix your issue.
