### ISSUE TITLE
Tagges as required for 1.18.2 mods but the dependency is lower version?

### ISSUE THREAD

**Issue by ardissaps** [AlexIIL/LibNetworkStack#7]

**Comment by AlexIIL** [comment]
It looks okay to me?

https://github.com/AlexIIL/LibNetworkStack/blob/6dd395a26a0542871613cff32fbc717e17cc18da/src/main/resources/fabric.mod.json#L17

**Comment by ardissaps** [comment]
> It looks okay to me?
> 
> https://github.com/AlexIIL/LibNetworkStack/blob/6dd395a26a0542871613cff32fbc717e17cc18da/src/main/resources/fabric.mod.json#L17

Would you like to update the curseforge file tag version? Coz the launcher unable to download because of that, appreciate if so. Thx
https://www.curseforge.com/minecraft/mc-mods/lib-network-stack

**Comment by AlexIIL** [comment]
Ah, woops - I must have missed that! I'll add it now.

**Comment by ardissaps** [comment]
> Ah, woops - I must have missed that! I'll add it now.

Many Thanks! :)
